---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	route(route)
	rag_answer(rag_answer)
	agent(agent)
	tools(tools)
	verify(verify)
	abstain(abstain)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> route;
	abstain --> finalize;
	agent -.-> finalize;
	agent -.-> tools;
	agent -.-> verify;
	rag_answer --> verify;
	route -.-> abstain;
	route -.-> agent;
	route -.-> rag_answer;
	tools -.-> agent;
	tools -.-> verify;
	verify -.-> agent;
	verify -.-> finalize;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
